// app/layout.tsx
import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Space_Mono,
  Monoton,
  Fredoka,
  Bowlby_One,
  Poppins,
} from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import SmoothScroll from "@/providers/SmoothScroll";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const spaceMono = Space_Mono({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-space-mono",
});
const bowlby = Bowlby_One({
  variable: "--font-bowlby",
  weight: ["400"],
  subsets: ["latin"],
});
const monoton = Monoton({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-disco",
});
const fredoka = Fredoka({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-fredoka",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: "800",
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Boogie Wheels",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${spaceMono.variable} ${fredoka.variable} ${monoton.variable} ${geistSans.variable} ${geistMono.variable} ${bowlby.variable} ${poppins.variable}`}
    >
      <body className="antialiased font-sans">
        <SmoothScroll />
        {children}
        <Footer />
      </body>
    </html>
  );
}
